name: FIRST

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
    
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2
        
      - name: RUN TESTS
        run: python3 -m pytest


 