name: FIRST

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
    
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v2

      - name: install dep
        run: 
          python -m pip install pytest
          sudo apt install 
            \python3-sphinx \
            python3-sphinx-autodoc-typehints \
            python3-sphinx-rtd-theme

      - name: RUN TESTS
        run: pytest


 